### PR TITLE
Updated Shrk Icon  

### PR DESCRIPTION
**Pull request by CPaulson42**

### CODE REVIEW

**Comment by man15h** [comment]
Hey @3FinTony you need to remove `.DS_Store` files first.

**Comment by CPaulson42** [comment]
Ok will do ,I thought  that was needed in the merge , for I am learning the
correct process  we decided to update the logo without a background also
will update the files

**Comment by CPaulson42** [comment]
@man15h updated

**Comment by man15h** [comment]
Hey @3FinTony , to avoid the conflicts in file, I just changed the folder structure. Please update the request with new format. Thanks

**Pull request closed without merging**
